prod:
  frontend_base_url:  http://byexample_clone.pl.localhost
  backend_base_url:   http://admin.byexample_clone.pl.localhost

staging:
  frontend_base_url:  http://byexample_clone.pl.localhost
  backend_base_url:   http://admin.byexample_clone.pl.localhost

dev:
  frontend_base_url:  http://byexample_clone.pl.localhost
  backend_base_url:   http://admin.byexample_clone.pl.localhost




all:
  pager_example_max_na_stronie: 2
  pager_project_max_na_stronie: 3
  pager_hint_max_na_stronie:    5